server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuisGustav0/ead-config-server-repo
          default-label: master
          username: LuisGustav0
          password: ${GIT_PASSWORD}

ead:
  configServer:
    username: configServer
    password: ${CONFIG_SERVER_PASSWORD}
  serviceRegistry:
    username: serviceRegistry
    password: ${SERVICE_REGISTRY_PASSWORD}

# Eureka
eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
